version: "3"

services:
  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    image: authservice:latest
    container_name: authservice
    env_file:
      - ./AuthService/.env
    ports:
      - "5000:8080"

  employeeservice:
    build:
      context: ./EmployeeService
      dockerfile: Dockerfile
    image: employeeservice:latest
    container_name: employeeservice
    env_file:
      - ./EmployeeService/.env
    ports:
      - "5001:8080"
