version: "3"

services:
  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/authservice:latest
    container_name: authservice
    ports:
      - "5000:8080"

  employeeservice:
    build:
      context: ./EmployeeService
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/employeeservice:latest
    container_name: employeeservice
    ports:
      - "5001:8080"
