CREATE TABLE Departments 
(
    DepartmentId NVARCHAR(450) NOT NULL DEFAULT LOWER(NEWID()) PRIMARY KEY,
    DepartmentName NVARCHAR(max) NOT NULL,
    Description NVARCHAR(max),
	CreatedDate DATETIME2(7) NOT NULL DEFAULT GETDATE(),
	UpdatedDate DATETIME2(7) NULL,
	IsDeleted BIT NOT NULL DEFAULT 0
);