CREATE TABLE Employees
(
	EmployeeId NVARCHAR(450) NOT NULL DEFAULT LOWER(NEWID())  PRIMARY KEY,
	FullName NVARCHAR(max) NOT NULL,
	Gender NVARCHAR(max) NOT NULL DEFAULT 'Other',
	DateOfBirth DATETIME2(7) NOT NULL,
	Hometown NVARCHAR(max) NOT NULL,
	AvatarImage NVARCHAR(max) NULL DEFAULT NULL,
    DepartmentId NVARCHAR(450) NOT NULL,
	PositionId NVARCHAR(450) NOT NULL,
	CreatedDate DATETIME2(7) NOT NULL DEFAULT GETDATE(),
	UpdatedDate DATETIME2(7) NULL,
	IsDeleted BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (DepartmentId) REFERENCES Departments (DepartmentId),
	FOREIGN KEY (PositionId) REFERENCES Positions (PositionId)
);