CREATE TABLE EmployeeLogs
(
    LogId NVARCHAR(450) NOT NULL DEFAULT LOWER(NEWID()) PRIMARY KEY,
    EmployeeId NVARCHAR(450) NOT NULL,
    Action NVARCHAR(MAX) NOT NULL,
    ActionDate DATETIME2(7) NOT NULL DEFAULT GETDATE()
);