name: Deploy services on AWS EC2

on:
  workflow_run: # Only trigger this workflow if these workflows are completed & success
    workflows:
      [
        "Build & Push AuthService image to Docker Hub",
        "Build & Push EmployeeService image to Docker Hub",
      ]
    types:
      - completed

jobs:
  deploy-ec2:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker Hub images
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/authservice:latest
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/employeeservice:latest

      - name: Stop & remove running docker containers
        run: |
          sudo docker stop authservice
          sudo docker stop employeeservice
          sudo docker rm authservice
          sudo docker rm employeeservice

      - name: Start new docker containers
        run: |
          sudo docker run -d --name authservice --env-file auth-service.env -p 5000:8080 ${{ secrets.DOCKERHUB_USERNAME }}/authservice:latest 
          sudo docker run -d --name employeeservice --env-file employee-service.env -p 5001:8080 ${{ secrets.DOCKERHUB_USERNAME }}/employeeservice:latest
