name: Manual deploy AWS ECR images to EC2

on:
  workflow_dispatch:
    inputs:
      authservice-image-tag:
        description: "AuthService ECR image tag (Ex: 689f6b98f81ecad9532698815495fc81440501b1)"
        required: true
        default: ""
      employeeservice-image-tag:
        description: "EmployeeService ECR image tag (Ex: 689f6b98f81ecad9532698815495fc81440501b1)"
        required: true
        default: ""

jobs:
  manual-deploy-aws-ecr-images-ec2:
    runs-on: self-hosted
    steps:
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | sudo docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URL }}
            
      - name: Pull Docker Hub images
        run: |
          sudo docker pull ${{ secrets.ECR_REGISTRY_URL }}/ems/authservice:${{ github.event.inputs.authservice-image-tag }}
          sudo docker pull ${{ secrets.ECR_REGISTRY_URL }}/ems/employeeservice:${{ github.event.inputs.employeeservice-image-tag }}

      - name: Stop & remove running docker containers
        run: |
          sudo docker stop authservice || true
          sudo docker stop employeeservice || true
          sudo docker rm authservice || true
          sudo docker rm employeeservice || true

      - name: Start new docker containers
        run: |
          sudo docker run -d \
            --name authservice \
            --env-file ~/EmployeeManagement/AuthService/.env \
            -p 5000:8080 \
            ${{ secrets.ECR_REGISTRY_URL }}/ems/authservice:${{ github.event.inputs.authservice-image-tag }}

          sudo docker run -d \
            --name employeeservice \
            --env-file ~/EmployeeManagement/EmployeeService/.env \
            -p 5001:8080 \
            ${{ secrets.ECR_REGISTRY_URL }}/ems/employeeservice:${{ github.event.inputs.employeeservice-image-tag }}
