name: Build & Push InfraCore commons to Nuget.org

on:
  push:
    branches:
      - develop
    paths:
      - "InfraCore/**"

jobs:
  publish-infracore-nugetorg:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: InfraCore

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack --configuration Release

      - name: Publish to NuGet
        run: dotnet nuget push "./bin/Release/*.nupkg" \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json
